version: 1.0.{build}

environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform:
 - x86

install:
 - git submodule update --init --recursive

test: off

for:
# ======================================
#      Windows
# ======================================
-
  matrix:
    only:
    - job_name: Windows

  build_script:
   - python setup.py
   - build.bat


 # ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux
  
  install:
   - sudo dpkg --add-architecture i386
   - sudo apt-get install -y wine32

  build_script:
   - python setup.py
   - rm -Rf ./wine
   - WINEPREFIX=~/.wine32 WINEARCH=win32 wineboot
   - ls
   - WINEPREFIX=~/.wine32 WINEARCH=win32 wine cmd /c build.bat
