version: 1.0.{build}

environment:
  matrix:
#    - job_name: Windows
#      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform:
 - x86

test: off

for:
# ======================================
#      Windows
# ======================================
#-
#  matrix:
#    only:
#    - job_name: Windows

#  build_script:
#   - python setup.py
#   - build.bat

#  install:
#   - git submodule update --init --recursive


# ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux
  
  install:
   - sudo dpkg --add-architecture i386
   - sudo apt-get install -y wine32
   - git submodule update --init --recursive

  build_script:
   - python setup.py
   - rm -Rf ./wine
   - WINEPREFIX=~/.wine32 WINEARCH=win32 wineboot
   - ls
   - WINEPREFIX=~/.wine32 WINEARCH=win32 wine cmd /c build.bat

  after_build:
   - cat "home/appveyor/projects/gta2-re/build_vc6/CMakeFiles/CMakeOutput.log"
   - cat "home/appveyor/projects/gta2-re/build_vc6/CMakeFiles/CMakeError.log"