version: 1.0.{build}

image: 
  - Visual Studio 2017
  - Ubuntu

platform:
 - x86

#clone_folder: c:\gta2_re

build_script:
 - python setup.py
 - build.bat

install:
 - git submodule update --init --recursive

test: off
