version: 1.0.{build}

image: 
  - Visual Studio 2017
  - Ubuntu

platform:
 - x86

#clone_folder: c:\gta2_re

build_script:
 - python setup.py

install:
 - git submodule update --init --recursive

test: off

for:
# ======================================
#      Windows
# ======================================
-
  matrix:
    only:
    - job_name: Windows

  build_script:
   - build.bat


 # ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux

  build_script:
   - wine build.bat