version: 1.0.{build}

environment:
  matrix:
    - job_name: Windows_VC2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - job_name: Windows_VC6
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

    - job_name: Linux_wine_VC6
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform:
 - x86

test: off

for:
# ======================================
#      Windows vc2019
# ======================================
-
  matrix:
    only:
    - job_name: Windows_VC2019

  build_script:
   - mkdir build_vc2019
   - cd build_vc2019
   - cmake.exe .. -G"Visual Studio 16 2019" -A Win32
   - cmake --build . --target decomp_main --config Release
   - cd ..

  artifacts:
    - path: build_vc2019/Release/decomp_main.exe
      name: windows_vc2019_main_exe

# ======================================
#      Windows vc6
# ======================================
-
  matrix:
    only:
    - job_name: Windows_VC6

  install:
   - git submodule update --init --recursive

  build_script:
   - python setup.py
   - build.bat
   - cd ../Scripts/bin_comp
   - python msvc_dump_func_data.py
   - ps: ./download_exe.ps1
   - pip install iced-x86
   - python compare_all_functions.py
   - cd ../../build_vc6

  artifacts:
    - path: build_vc6/Release/decomp_main.exe
      name: windows_vc6_main_exe

# ======================================
#      Linux vc6
# ======================================
-
  matrix:
    only:
    - job_name: Linux_wine_VC6
  
  install:
   - sudo apt-get install -y xvfb wine32 python3-venv
   - git submodule update --init --recursive

  build_script:
   - python3 setup.py
   - rm -Rf ./wine
   - WINEPREFIX=~/.wine32 WINEDEBUG=-all WINEARCH=win32 xvfb-run wineboot
   - WINEPREFIX=~/.wine32 WINEDEBUG=-all WINEARCH=win32 xvfb-run wine cmd /c build.bat
   - cd Scripts/bin_comp
   - wget 'https://cdn.discordapp.com/attachments/1187316940532891689/1299193521177104434/10.5.exe?ex=671c4fc1&is=671afe41&hm=d017ee3e91a26587c878b65a4ccfc14083d67cd3396205ad8c58cddeb8f62d8a&' 10.5.exe
   - python3 msvc_dump_func_data.py
   - python3 -m venv ./venv
   - ./venv/bin/pip install iced-x86
   - ./venv/bin/python compare_all_functions.py
   - cd ../../...

  artifacts:
    - path: build_vc6/Release/decomp_main.exe
      name: linux_vc6_main_exe
