version: 1.0.{build}

environment:
  matrix:
    - job_name: Windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - job_name: Linux
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

platform:
 - x86

#clone_folder: c:\gta2_re

build_script:
 - python setup.py

install:
 - git submodule update --init --recursive

test: off

for:
# ======================================
#      Windows
# ======================================
-
  matrix:
    only:
    - job_name: Windows

  build_script:
   - build.bat


 # ======================================
#      Linux
# ======================================
-
  matrix:
    only:
    - job_name: Linux
  
  install:
   - sudo apt-get install -y wine-stable

  build_script:
   - wine build.bat