#pragma once

#include "Function.hpp"
#include "Globals.hpp"

struct Debug
{
    EXPORT void Init_4ABBD0();

    EXPORT bool HaveOnlyFrenchGtx_4AC200();
};
EXTERN_GLOBAL(Debug, gDebug_67D52C);

EXTERN_GLOBAL(bool, gDo_infinite_lives_67D4C9);
EXTERN_GLOBAL(bool, bLimit_recycling_67D4CA);
EXTERN_GLOBAL(bool, bDo_invulnerable_67D4CB);
EXTERN_GLOBAL(bool, bLog_input_67D4CC);
EXTERN_GLOBAL(bool, bSkip_right_67D4E4);
EXTERN_GLOBAL(bool, bSkip_mission_67D4E5);
EXTERN_GLOBAL(bool, bLog_collisions_67D4E6);
EXTERN_GLOBAL(bool, bSkip_bottom_67D4E7);
EXTERN_GLOBAL(bool, bSkip_quit_confirm_67D4E8);
EXTERN_GLOBAL(bool, bDo_iain_test_67D4E9);
EXTERN_GLOBAL(bool, bSkip_draw_67D4EA);
EXTERN_GLOBAL(bool, bDo_release_replay_67D4EB);
EXTERN_GLOBAL(bool, bSkip_traffic_lights_67D4EC);
EXTERN_GLOBAL(bool, gCheatOnlyElvisPeds_67D4ED);
EXTERN_GLOBAL(bool, bDo_corner_window_67D4EE);
EXTERN_GLOBAL(bool, bSkip_dummies_67D4EF);
EXTERN_GLOBAL(bool, bDo_load_savegame_67D4F0);
EXTERN_GLOBAL(bool, gCheatGet99Lives_67D4F1);
EXTERN_GLOBAL(bool, bDo_show_horn_67D4F2);
EXTERN_GLOBAL(bool, bIgnore_replay_header_67D4F3);
EXTERN_GLOBAL(bool, bPlay_replay_67D4F4);
EXTERN_GLOBAL(bool, bDont_get_car_back_67D4F5);
EXTERN_GLOBAL(bool, gCheatUnknown_67D4F6);
EXTERN_GLOBAL(bool, gCheatUnlimitedElectroGun_67D4F7);
EXTERN_GLOBAL(bool, bDo_test_67D4F8);
EXTERN_GLOBAL(bool, bSkip_police_67D4F9);
EXTERN_GLOBAL(bool, bDo_show_traffic_lights_info_67D4FA);
EXTERN_GLOBAL(bool, bExplodingScoresOff_67D4FB);
EXTERN_GLOBAL(bool, bShow_brief_number_67D504);
EXTERN_GLOBAL(bool, bSkip_slopes_67D505);
EXTERN_GLOBAL(bool, bSkip_user_67D506);
EXTERN_GLOBAL(bool, bSkip_fire_engines_67D53A);
EXTERN_GLOBAL(bool, bSkip_frontend_67D53B);
EXTERN_GLOBAL(bool, bIsFrench_67D53C);
EXTERN_GLOBAL(bool, bDo_brian_test_67D544);
EXTERN_GLOBAL(bool, bSkip_lid_67D546);
EXTERN_GLOBAL(bool, bShow_player_names_67D54C);
EXTERN_GLOBAL(bool, bKeep_weapons_after_death_67D54D);
EXTERN_GLOBAL(bool, bSkip_window_check_67D54E);
EXTERN_GLOBAL(bool, bDo_show_physics_67D54F);
EXTERN_GLOBAL(bool, bSkip_trains_67D550);
EXTERN_GLOBAL(bool, bSkip_buses_67D558);
EXTERN_GLOBAL(bool, bDo_show_ids_67D559);
EXTERN_GLOBAL(bool, bDo_police_1_67D568);
EXTERN_GLOBAL(bool, bDo_police_2_67D569);
EXTERN_GLOBAL(bool, bDo_police_3_67D56A);
EXTERN_GLOBAL(bool, bSkip_top_67D574);
EXTERN_GLOBAL(bool, bSkip_recycling_67D575);
EXTERN_GLOBAL(bool, gDo_show_input_67D576);
EXTERN_GLOBAL(bool, bSkip_skidmarks_67D585);
EXTERN_GLOBAL(bool, bNo_annoying_chars_67D586);
EXTERN_GLOBAL(bool, bDo_show_imaginary_67D588);
EXTERN_GLOBAL(bool, bDo_show_camera_67D58A);
EXTERN_GLOBAL(bool, bSkip_replay_sync_check_67D594);
EXTERN_GLOBAL(bool, bDo_show_junc_ids_67D5B0);
EXTERN_GLOBAL(bool, bLog_random_extra_67D5BC);
EXTERN_GLOBAL(bool, bConstant_replay_save_67D5C4);
EXTERN_GLOBAL(bool, bDo_blood_67D5C5);
EXTERN_GLOBAL(bool, bDo_mike_67D5CC);
EXTERN_GLOBAL(bool, bShow_hidden_faces_67D5CD);
EXTERN_GLOBAL(bool, bLog_random_67D5FC);
EXTERN_GLOBAL(bool, bDo_show_instruments_67D64C);
EXTERN_GLOBAL(bool, bSkip_particles_67D64D);
EXTERN_GLOBAL(bool, bSkip_tiles_67D655);
EXTERN_GLOBAL(bool, bGet_all_weapons_67D684);
EXTERN_GLOBAL(bool, gDo_miss_logging_67D6BC);
EXTERN_GLOBAL(bool, gShow_cycle_67D6BD);
EXTERN_GLOBAL(bool, bSkip_audio_67D6BE);
EXTERN_GLOBAL(bool, bSkip_left_67D6BF);
EXTERN_GLOBAL(bool, bLog_directinput_67D6C0);
EXTERN_GLOBAL(bool, bDo_sync_check_67D6C1);
EXTERN_GLOBAL(bool, bDo_3d_sound_67D6C2);
EXTERN_GLOBAL(bool, bSkip_ambulance_67D6C9);
EXTERN_GLOBAL(bool, bDo_show_object_ids_67D6CA);
EXTERN_GLOBAL(bool, bDo_free_shopping_67D6CD);
EXTERN_GLOBAL(bool, bDo_debug_keys_67D6CF);
EXTERN_GLOBAL(bool, gDo_text_id_test_67D6D0);
EXTERN_GLOBAL(bool, bLog_routefinder_67D6D1);
EXTERN_GLOBAL(bool, bDo_show_timing_67D6DC);
EXTERN_GLOBAL(bool, bDo_exit_after_replay_67D6E4);
EXTERN_GLOBAL(bool, bDo_show_collision_box_67D6E5);
EXTERN_GLOBAL(bool, gDo_show_counter_67D6E6);
EXTERN_GLOBAL(bool, bShow_all_arrows_67D6E7);
EXTERN_GLOBAL(bool, bDo_kill_phones_on_answer_67D6E8);